# Site settings
title: Dr Sudarshan
description: > # this means to ignore newlines until "baseurl:"
 
 
  
baseurl:  # the subpath of your site, e.g. /blog/
url: arya2331.github.io # the base hostname & protocol for your site
twitter_username: Sudarshan

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
# http://svmiller.com
